title: ISV Playbook
description: ISV Playbook is content repository to help Microsoft Partners with onboarding, knowledge sharing and innovation.
theme: just-the-docs

url: https://isvplaybook.github.io/isvplaybook/

# aux_links:
#   Template Repository: https://github.com/just-the-docs/just-the-docs-template

nav_enabled: true
heading_anchors: true